id: A499A0890
title: Invocation
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.716470
  last_modified_at: 2022-03-01 21:52:25.716473
