id: A499A0890
title: 5. The simile of a hidden treasure beneath the house of some poor person
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.705081
  last_modified_at: 2022-03-01 21:52:25.705088
