id: A499A0890
title: 11. The story of *Sadāpramuktaraśmi and *Anantaraśmi
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.690405
  last_modified_at: 2022-03-01 21:52:25.690411
