id: A499A0890
title: 1. The simile of a tathāgata in a lotus
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.681740
  last_modified_at: 2022-03-01 21:52:25.681747
