id: A499A0890
title: 2. The simile of honey shielded by bees
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.696938
  last_modified_at: 2022-03-01 21:52:25.696941
