id: A499A0890
title: 8. The simile of the future universal emperor in the womb of a poor, depressed
  woman
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.712778
  last_modified_at: 2022-03-01 21:52:25.712782
