id: A499A0890
title: 6. The simile of a sprout in the seed
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.707834
  last_modified_at: 2022-03-01 21:52:25.707837
