id: A499A0890
title: 4. The simile of a gold nugget in excrement
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.701613
  last_modified_at: 2022-03-01 21:52:25.701621
