id: A499A0890
title: 9. The simile of golden figures within burned clay molds
type: translation
source_metadata:
  languages:
  - bo
  - zh
  - en
  datatype: PlainText
  created_at: 2022-03-01 21:52:25.715002
  last_modified_at: 2022-03-01 21:52:25.715005
